{
    'name': 'Fish Farm Management',
    'version': '18.0.1.0.0',
    'summary': 'Comprehensive Fish Farm Management System',
    'description': """
        Manage fish farm operations including ponds, breeding cycles, 
        harvesting, costs, and integration with Odoo modules
    """,
    'category': 'Industries',
    'author': 'NextGen Systems',
    'website': 'https://www.nextgensystems.net',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'stock',
        'account',
        'product',
        'purchase',
        'sale',
        'mrp',
        'hr',
        'analytic',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/dashboard_actions.xml',
        #'views/dashboard_views.xml',
        'views/farm_views.xml',
        'views/pond_views.xml',
        'views/breeding_cycle_views.xml',
        'views/harvest_views.xml',
        'views/cost_distribution_views.xml',
        'views/fish_type_views.xml',
        'views/sector_views.xml',
        'views/segment_views.xml',
        'views/res_config_settings.xml',
        'report/harvest_report.xml',
        'report/breeding_cycle_report.xml',
        'report/cost_analysis_report.xml',
        'report/inventory_report.xml',
        #'views/templates.xml',
        #'views/translation_templates.xml',
        'views/menu.xml',
        #'static/src/xml/dashboard_template.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'fish_farm_management/static/src/xml/dashboard_template.xml',
            'fish_farm_management/static/src/js/dashboard.js',
            'fish_farm_management/static/src/css/dashboard.css',
            'fish_farm_management/static/src/css/styles.css',
            'fish_farm_management/static/lib/chart/chart.umd.js',
            #'fish_farm_management/static/src/js/translation.js',
        ],
        'web.assets_qweb': [  
            #'fish_farm_management/static/src/xml/dashboard_template.xml',
        ],
    },
}