# -*- coding: utf-8 -*-
{
    "name": "Fish Farm Management",
    "version": "18.0.1.0.0",
    "summary": "Comprehensive ERP for fish farms: operations, costing, reporting.",
    "description": (
        "Complete ERP for fish farm management, including:\n"
        "- Tracking fish lifecycle (weight, count, type)\n"
        "- Feeding and stock management\n"
        "- Health monitoring and disease logging\n"
        "- Harvest reporting and performance analysis"
    ),
    "author": "NextGen Systems",
    "website": "https://nextgensystems.net",
    "category": "Industries/Agriculture",
    "depends": [
        "base",
        "product",
        "mail",
        'maintenance',
        "account",
        #'analytic',
        "stock",
        "sale_management",
        "purchase",
        "mrp",
        "crm",
        "hr",
        "hr_expense",
        "hr_payroll",
        "fish_farm_product_extension",
    ],
    "data": [
        "security/fish_farm_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        #'data/product_data.xml',
        #'data/analytic_tag_data.xml',
        "views/fish_farm_views.xml",
        "views/fish_farm_dashboard_views.xml",
        "views/sector_views.xml",
        "views/slice_views.xml",
        "views/pond_views.xml",
        "views/fish_stocking_views.xml",
        'views/pond_feeding_actions.xml',
        "views/pond_feeding_views.xml",
        "views/pond_cost_views.xml",
        "views/analytic_account_extension_views.xml",
        "views/harvest_delivery_views.xml",
        "views/harvest_record_views.xml",
        "views/harvest_sorting_views.xml",
        "views/fish_health_views.xml",
        "views/water_quality_views.xml",
        "views/equipment_views.xml",
        "views/maintenance_request_views_extension.xml",
        "views/production_plan_views.xml",
        "views/batch_traceability_views.xml",
        "views/fish_growth_model_views.xml",
        "views/fish_growth_measurement_views.xml",
        "views/fish_farm_settings_views.xml",
        "wizards/report_wizard_views.xml",
        "views/menu_items.xml",
        "reports/report_actions.xml",
        "reports/report_pond_cost_analysis_template.xml",
        "reports/report_harvest_performance_template.xml",
        "reports/report_supplies_consumption_template.xml",
        "reports/report_fish_health_water_quality_template.xml",
        "reports/report_sales_profitability_template.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "fish_farm_management/static/src/lib/chart/chart.umd.js",
            "fish_farm_management/static/src/js/dashboard_main.js",
            "fish_farm_management/static/src/xml/fish_farm_dashboard.xml",
            "fish_farm_management/static/src/css/dashboard.css",
            "fish_farm_management/static/src/js/excel_export.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
