services:
  postgres:
    image: postgres:13
    env:
      POSTGRES_DB: ci_db
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - 5432:5432
    options: >-
      --health-cmd "pg_isready -U odoo -d ci_db"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install odoo pylint pylint-odoo

  - name: Configure minimal odoo.conf
    run: |
      cat <<EOF > odoo.conf
      [options]
      addons_path = .,/usr/lib/python3/dist-packages/odoo/addons
      db_host = localhost
      db_port = 5432
      db_user = odoo
      db_password = odoo
      logfile = /tmp/odoo-ci.log
      EOF

  - name: Initialize database and install module
    run: |
      odoo-bin -c odoo.conf -d ci_db --db-filter=ci_db$ -i fish_farm_management --stop-after-init

  - name: Check Odoo log for errors
    run: |
      cat /tmp/odoo-ci.log